#ifndef SERIALIZERS_H
#define SERIALIZERS_H

#include "influxlogger/configuration.h"
#include "tpms/rtl433_payload.h"
#include "app/user_data.h"
#include "app/app_data.h"
#include "app/custom_preset.h"
#include "app/data_processing.h"
#include "app/app_config.h"
#include "can/can_frequencies.h"
#include "lapcounter/new_lap.h"
#include "lapcounter/lap_counter.h"
#include "lapcounter/lapcounter.h"
#include "data/telemetry_lap_data.h"
#include "data/extra.h"
#include "data/vehicle_state.h"
#include "data/as_commands.h"
#include "actions/command.h"
#include "actions/file_transaction.h"
#include "mongodb/lapcounter_lap_records.h"
#include "mongodb/lapcounter_lap_times.h"
#include "mongodb/lapcounter_layout.h"
#include "configs/car_config.h"
#include "configs/telemetry_config.h"
#include "configs/forwarder_config.h"
#include "configs/session_config.h"
#include "sessions/gpsSession.h"
#include "telemetry/statistics.h"
#include "telemetry/gps_maps.h"
#include "telemetry/error.h"
#include "telemetry/odometer.h"
#include "telemetry/login_data.h"
#include "telemetry/wait_ready.h"
#include "telemetry/status.h"
#include "handcart/settings.h"

#endif