syntax = "proto3";

package Configs;

message NtripClient
{
    string casterHost = 1;
    int32 casterPort = 2;
    string mountPoint = 3;
    string username = 4;
    string password = 5;
}

message GpsDev
{
    oneof address {
        string path = 1;
        string ip = 2;
    }
    string mode = 3;
    int32 tcpPort = 4;
    bool enabled = 5;
    oneof SpeedOrPort{
        int32 speed = 6;
        int32 port = 7;
    }
}

message ForwarderConfig 
{
    repeated GpsDev gpsDevice = 1;
    NtripClient ntripClient = 2;
    string mode = 3;
}
